export enum RtoSignalEnum {
  CANCELLED = 'CANCELLED',
  TAG = 'TAG',
  NOTE = 'NOTE',
  REFUNDED = 'REFUNDED',
  COURIER_LEOPARDS = 'COURIER_LEOPARDS',
  COURIER_TCS = 'COURIER_TCS',
  COURIER_MNP = 'COURIER_MNP',
  COURIER_POSTEX = 'COURIER_POSTEX',
  MANUAL = 'MANUAL',
}
